In [12]:
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
arr=arr*2
print(arr)

[ 2  4  6  8 10]


In [16]:
arr1=np.array(([1,2,3,4,5],[2,3,4,5,6]))
print(*arr1)
arr1.shape

[1 2 3 4 5] [2 3 4 5 6]


(2, 5)

In [18]:
arr[1:4]

array([4, 6, 8])

In [17]:
arr[1]

np.int64(4)

In [20]:
a=np.array([[1,2,3,4,5],[5,6,7,8,9],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


In [21]:
##a[rows,colums]-rows and columns are indexed from 0
a[1,3]

np.int64(8)

In [23]:
a.size

15

In [14]:
arr.shape

(5,)

In [22]:
a.ndim

2

In [26]:
normal_arr=np.array([[2,3,4,5,6],[9,8,7,6,5]])
normal_arr


array([[2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [29]:
sliced_arr=normal_arr[:,2:]
sliced_arr

array([[4, 5, 6],
       [7, 6, 5]])

In [30]:
zero_matrix=np.zeros((3,4))
zero_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
one_matrix=np.ones((3,4))
one_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
empty_matrix=np.empty((3,4))
empty_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
rangeOfNum=np.arange(10)
rangeOfNum

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
rangeWithStep=np.arange(0,10,2) ##start,stop,step
rangeWithStep

array([0, 2, 4, 6, 8])

In [ ]:
arr=np.array([5,2,1,3,4,5,8,7])
arr.sort() ##sorting in ascending order,sort() is combination of quick sort,merge sort and insertion sort ,timsort
arr

array([1, 2, 3, 4, 5, 5, 7, 8])

In [40]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
np.concatenate((arr1,arr2)) ##concatenate two arrays

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [45]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
import numpy as np

### this is third heading



## this is sample code


## This is a markdown block


In [10]:
print("this is s python block")

this is s python block
